input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "eztrade-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug { metadata => false }
  }
}
