apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payments.fullname" . }}
  labels: {{- include "payments.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels: {{- include "payments.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "payments.selectorLabels" . | nindent 8 }}
      annotations:
        dapr.io/enabled: "{{ .Values.dapr.enabled }}"
        dapr.io/app-id: "{{ .Values.dapr.appId }}"
        dapr.io/app-port: "{{ .Values.dapr.appPort }}"
        dapr.io/config: "{{ .Values.dapr.config }}"
    spec:
      containers:
        - name: payments
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ConnectionStrings__Default
              value: "{{ .Values.connectionString }}"
            - name: Authentication__Issuer
              value: "{{ .Values.authentication.issuer }}"
            - name: Authentication__Authority
              value: "{{ .Values.authentication.authority }}"
            - name: Authentication__Audience
              value: "{{ .Values.authentication.audience }}"
            - name: ElasticLogging__Enabled
              value: "{{ .Values.elasticLogging.enabled }}"
            - name: ElasticLogging__EnableConsoleSink
              value: "{{ .Values.elasticLogging.enableConsoleSink }}"
            - name: ElasticLogging__LogDirectory
              value: "{{ .Values.elasticLogging.logDirectory }}"
            - name: ElasticLogging__MinimumLevel
              value: "{{ .Values.elasticLogging.minimumLevel }}"
            - name: ElasticLogging__RetainedFileCountLimit
              value: "{{ .Values.elasticLogging.retainedFileCountLimit }}"
            - name: Nacos__Enabled
              value: "{{ .Values.nacos.enabled }}"
            - name: Nacos__LoadConfiguration
              value: "{{ .Values.nacos.loadConfiguration }}"
            - name: Nacos__RegisterService
              value: "{{ .Values.nacos.registerService }}"
            - name: Nacos__ServerAddress
              value: "{{ .Values.nacos.serverAddress }}"
            - name: Nacos__NamespaceId
              value: "{{ .Values.nacos.namespaceId }}"
            - name: Nacos__Group
              value: "{{ .Values.nacos.group }}"
            - name: Nacos__ClusterName
              value: "{{ .Values.nacos.clusterName }}"
            - name: Nacos__ServiceName
              value: "{{ .Values.nacos.serviceName }}"
            - name: Nacos__ConfigDataId
              value: "{{ .Values.nacos.configDataId }}"
            - name: Nacos__InstancePort
              value: "{{ .Values.nacos.instancePort }}"
            - name: RabbitMq__Enabled
              value: "{{ .Values.rabbitMq.enabled }}"
            - name: RabbitMq__HostName
              value: "{{ .Values.rabbitMq.hostName }}"
            - name: RabbitMq__Port
              value: "{{ .Values.rabbitMq.port }}"
            - name: RabbitMq__UserName
              value: "{{ .Values.rabbitMq.userName }}"
            - name: RabbitMq__Password
              value: "{{ .Values.rabbitMq.password }}"
            - name: RabbitMq__VirtualHost
              value: "{{ .Values.rabbitMq.virtualHost }}"
            - name: RabbitMq__ExchangeName
              value: "{{ .Values.rabbitMq.exchangeName }}"
            - name: RabbitMq__PrefetchCount
              value: "{{ .Values.rabbitMq.prefetchCount }}"
            - name: RabbitMq__ClientProvidedName
              value: "{{ .Values.rabbitMq.clientProvidedName }}"
          resources: {{- toYaml .Values.resources | nindent 12 }}
