apiVersion: v1
kind: Service
metadata:
  name: {{ include "payments.fullname" . }}
  labels: {{- include "payments.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector: {{- include "payments.selectorLabels" . | nindent 4 }}
